worker_processes  auto;
# 	pid /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    server {
        listen 4433 ssl;
        server_name localhost;

        # --- Cấu hình PQC và Chứng chỉ ---
        ssl_protocols         TLSv1.3;
        # Sử dụng đường dẫn mà image mong đợi
        ssl_certificate       /opt/nginx/pki/server.crt;
        ssl_certificate_key   /opt/nginx/pki/server.key;
        
        # Thống nhất dùng Kyber768 để dễ test
        ssl_ecdh_curve        mlkem768;

        # Chuyển tiếp log ra console của Docker
        access_log /dev/stdout;
        error_log /dev/stderr info; # Đặt ở mức info để xem nhiều thông tin hơn

        # --- Reverse Proxy ---
        location / {
             # Chuyển tiếp mọi yêu cầu đến dịch vụ 'backend'
             proxy_pass http://backend:8000;
             proxy_set_header Host $host;
             proxy_set_header X-Real-IP $remote_addr;
             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
             proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
